### ISSUE TITLE
How to test macro expansion error messages?

### ISSUE THREAD

**Issue by olafurpg** [directembedding/directembedding#21]
I made an edit to improve the macro expansion error message with `c.abort` [here](https://github.com/olafurpg/directembedding/blob/refactor/directembedding/src/main/scala/ch/epfl/directembedding/transformers/ReifyAsEmbedding.scala#L23). Is there any proper way to test this functionality? Something like this

```scala
 "lift" should "give a friendly error when a reifyAs annotation is missing" in {
  interrupt[CompilerError???] {
     testReify(implicit collec =>
     lift {
       ObjectExample.missingAnnotation
     }) should be(List(???))
   }
}
```

**Comment by olafurpg** [comment]
@vjovanov

**Comment by vjovanov** [comment]
Yes there is, please look at [scala-records](https://github.com/scala-records/scala-records/blob/master/tests/src/main/scala/records/test/TypecheckingMacros.scala#L39).

**Comment by olafurpg** [comment]
Great, that was exactly what I was looking for.

Where do you think it's best to put the `TypecheckingMacros` module? One option is to create a `tests` project like with scala-records (pretty cool), another to simply include it with directembedding (not so cool).

**Comment by vjovanov** [comment]
Let's do cool things.
