### ISSUE TITLE
Make the library configurable. 

### ISSUE THREAD

**Issue by vjovanov** [directembedding/directembedding#7]
The user should parametrize the macro with a method that needs to be called for execution.

**Comment by vjovanov** [comment]
@olafurpg is this fixed?

**Comment by olafurpg** [comment]
Yes, this was fixed with the last PL

**Comment by vjovanov** [comment]
Fixed by #24

**Comment by olafurpg** [comment]
To be precise, fixed by #23, and improved by #24.
