### ISSUE TITLE
Reification of language constructs should be configurable.

### ISSUE THREAD

**Issue by vjovanov** [directembedding/directembedding#8]
For each DSL there should be a configurable object containing the reification rules for the language constructs. For example, if we would like to reify the `if` construct in a DSL to `IF` we would provide:
```
object DSLVirtualization {
  @reifyAs(IF)
  def __ifThenElse[T](c: Boolean, t: => T, e: => T): T = ???
}
```

Then the library would translate the DSL code: 
```
dsl { 
  ... // original code
}
```
into:
```
virtualize {
   import EmbeddedControls._ // re-wires all virtualized constructs to their original state
   {
     import DSLVirtualization._ // configurable
     // original code
   }
}
```

Here `virtualize` is a language [virtualization transformer](https://github.com/scala-yinyang/scala-yinyang/blob/master/components/core/src/transformers/LanguageVirtualization.scala), `EmbeddedControls` are undoing virutalization as in [scala-yinyang](https://github.com/scala-yinyang/scala-yinyang/blob/master/components/paradise/src/EmbeddedControls.scala), and `DSLVirtualizaiton` is configurable by the DSL library author.

**Comment by olafurpg** [comment]
See question in [this](https://github.com/olafurpg/directembedding/commit/0c88c1877e6c7dbc757138c45e36d0859f4e0072#commitcomment-10237660) comment, @vjovanov

**Comment by olafurpg** [comment]
Could you take a look at the questions in 461f652 @vjovanov?

**Comment by olafurpg** [comment]
Could you take a look at [this](https://github.com/olafurpg/directembedding/commit/593b8c0bbd655e84d377e658f42fd0a4c0c29542#commitcomment-10448077) question? @vjovanov

**Comment by olafurpg** [comment]
Also [this](https://github.com/olafurpg/directembedding/commit/868a9da42bc813146b981260fa1e01010d31545a#commitcomment-10457212) question, @vjovanov.

**Comment by olafurpg** [comment]
This issue is almost fixed now, there are only a few minor things left to improve. Could you take a look at the questions in the commit 32d0deb?
@vjovanov
